# Created by trellis-cli v0.9.0
# Documentation: https://roots.io/trellis/docs/wordpress-sites/

wordpress_sites:
  rentalspot.gr:
    site_hosts:
    - canonical: rentalspot.test
      redirects:
      - www.rentalspot.test
    local_path: ../site
    admin_email: admin@rentalspot.test
    multisite:
      enabled: false
    ssl:
      enabled: false
      provider: self-signed
    cache:
      enabled: false
