# Created by trellis-cli v0.9.0
# Documentation: https://roots.io/trellis/docs/wordpress-sites/

wordpress_sites:
  rentalspot.gr:
    site_hosts:
    - canonical: rentalspot.gr
      redirects:
      - www.rentalspot.gr
    local_path: ../site
    branch: master
    repo: git@github.com:Giannisduke/rentalspot.git
    repo_subtree_path: site
    multisite:
      enabled: false
    ssl:
      enabled: false
      provider: letsencrypt
    cache:
      enabled: false
